### PR TITLE
sso: remove old cipher fallback

### PR DESCRIPTION
**Pull request by jphines**
## Problem

There is a legacy fallback cipher that was used when we migrated session encryption schemas. This legacy fallback is no longer used and adds needless complexity.

## Solution

We should remove the legacy fallback cipher.

## Notes

This removes the legacy fallback cipher in both sso proxy and authenticator.

Fixes https://github.com/buzzfeed/sso/issues/41
Fixes https://github.com/buzzfeed/sso/issues/42

### CODE REVIEW

**Comment by jphines** [comment]
Ready For Review @shrayolacrayon 
cc/ @buzzfeed/infra-security

**Comment by shrayolacrayon** [comment]
This looks great! ✂️ 
You can also remove `internal/pkg/payloads` if it's not already gone.

**Comment by jphines** [comment]
@shrayolacrayon removed those pkgs

**Comment by shrayolacrayon** [comment]
lgtm!

**Comment by sporkmonger** [comment]
Did this fix #29? Can that be closed now?

**Pull request merged**
